language: node_js
node_js:
  - "0.10"
  
before_install:
  - sudo apt-get -y -q update && sudo apt-get install -y -q graphicsmagick
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24



after_script:
  - bash -c ./start.sh &
  - sleep 6
  - bash -c ./screenshot.sh 1>/tmp/out 2>/tmp/err
 # - ls -l /tmp/screenshot.png && 
